// This file generated by ngrestcg
// For more information, please visit: https://github.com/loentar/ngrest

#ifndef EDD_API_H
#define EDD_API_H

#include <ngrest/common/Service.h>

#include <string>
#include <list>
#include "lista.h"

struct estudianteSerial{
  std::string id;
  std::string nombre;
};

// *location: edd_api
class edd_api: public ngrest::Service
{
public:
    // To invoke this operation from browser open: http://localhost:9098/edd_api/World!

    // *method: POST
    // */location: /insertarEstudiante/{e}
    std::string insertarEstudiante(estudianteSerial e);


    // *method: POST
    // */location: /getEstudiante/{id}
    std::string getEstudiante(const std::string& id);

    // *method: GET
    // */location: /getEstudiantes
    std::list<estudianteSerial> getEstudiantes();
};


#endif // EDD_API_H
